title: Takuro Inoue
description: 職務経歴書は定期的にアップデートしていますので常に最新の状態を維持しています。
logo: https://raw.githubusercontent.com/takuro-inoue1913/resume/master/assets/img/takuro_icon.png
google_analytics:
is_user_page: true
theme: jekyll-theme-minimal
